blueprint:
  name: TX Gesture - Swipe Up Control
  description: >
    Responds to a Swipe Up gesture from a Sonoff TX Ultimate panel
    by turning on the specified targets.
  domain: automation

  input:
    gesture_entity:
      name: Gesture Sensor
      selector:
        entity:
          domain: binary_sensor

    targets_to_toggle:
      name: Targets to Toggle
      default: []
      selector:
        target:

mode: single

trigger:
  - platform: state
    entity_id: !input gesture_entity
    from: 'off'
    to: 'on'

condition:
  - condition: template
    value_template: >
      {{ (targets_to_toggle | length) > 0 }}

action:
  - service: system_log.write
    data:
      message: "Swipe Up Triggered: {{ trigger.entity_id }}"
      level: info

  - service: light.toggle
    target: !input targets_to_toggle
