blueprint:
  name: TX Gesture - Swipe Up Control
  description: >
    Toggles the selected targets when a gesture (binary sensor) changes from off to on.
  domain: automation

  input:
    gesture_entity:
      name: Gesture Sensor
      selector:
        entity:
          domain: binary_sensor

    targets_to_toggle:
      name: Targets to Toggle
      selector:
        target:

mode: single

trigger:
  - platform: state
    entity_id: !input gesture_entity
    from: 'off'
    to: 'on'

action:
  - service: system_log.write
    data:
      message: "Gesture triggered: {{ trigger.entity_id }}"
      level: info

  - service: light.toggle
    target: !input targets_to_toggle
